language: python
python:
  - "3.6"
  - "3.7"
  - "3.8"
#  - "3.9"  # does not work with tensorflow yet

# install dependencies
install:
  - pip install .[tests]

# run tests
script:
  - pytest tests/
