language: python
python:
  - "3.6.12"  # specifying minor version, because travis CI only tests the .0 version otherwise
  - "3.7.9"
  - "3.8.6"
#  - "3.9"  # does not work with tensorflow yet

# install dependencies
install:
  - pip install .[tests]

# run tests
script:
  - pytest tests/
